In [1]:
import numpy as np
data = np.array([21,22,23,24])
print(data)
print(data.shape)
print(data.size)
print(data.ndim)
print(data[2])

[21 22 23 24]
(4,)
4
1
23


In [10]:
import numpy as np
data = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(data)
print(data.shape)
print(data.size)
print(data.ndim)
print(data[2,2])

[[21 22 23]
 [24 25 26]
 [27 28 29]]
(3, 3)
9
2
29


In [12]:
import numpy as np
data = np.array([[21,22,23],[24,25,26],[27,28,29],[30,31,32]])
print(data)
print(data.shape)
print(data.size)
print(data.ndim)
print(data[2,1])

[[21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]]
(4, 3)
12
2
28
