In [ ]:
# np.arange(start, stop, step, dtype=None): Return evenly spaced values within a given interval.
# in depth

import numpy as np
arr = np.arange(0, 10, 2, dtype=int)
print(arr)

arr_float = np.arange(0.5,8.5,1.0)
print(arr_float)

arr_des = np.arange(10,0,-2)
print(arr_des)

[0 2 4 6 8]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
[10  8  6  4  2]


In [10]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None): Return 
# evenly spaced numbers over a specified interval.

arr,step = np.linspace(0,10,5,endpoint=True,retstep=True)
print(arr)
print("Step Size:",step)

arr_no_end = np.linspace(0,10,5,endpoint=False)
print(arr_no_end)

single = np.linspace(5,5,1)
print(single)

[ 0.   2.5  5.   7.5 10. ]
Step Size: 2.5
[0. 2. 4. 6. 8.]
[5.]
